InterPayIR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from interpay import views
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView

# from two_factor.urls import urlpatterns as tf_urls
# from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'session_security/', include('session_security.urls')),

    # url(r'^$', TemplateView.as_view(template_name="main_page.html")),
    # url(r'^home/', TemplateView.as_view(template_name="home.html")),
    # url(r'^wallets/', TemplateView.as_view(template_name="wallets.html")),
    # url(r'^trans-history/', TemplateView.as_view(template_name="trans_history.html")),
    # url(r'^reports/', TemplateView.as_view(template_name="reports.html"), name='reports'),
    # url(r'^general/', TemplateView.as_view(template_name="home.html"), name='general'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^$', views.main_page),
    url(r'^home/', views.home),
    url(r'^wallets/', views.wallets),
    url(r'^trans-history/', views.trans_history),
    url(r'^reports/', views.reports, name='reports'),
    url(r'^general/', views.general, name='general'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^verif/$', views.verify_user, name='verif'),
    url(r'^sms/$', views.send_sms, name='sms'),
    url(r'^retrieve_pass/$', views.retrieve_pass, name='retrieve_pass'),
    url(r'^top-up/', views.recharge_account, name='recharge_account'),
    url(r'^bank-accounts/', views.bank_accounts, name='bank_accounts'),

]

urlpatterns += i18n_patterns(
    # url(r'^accounts/', include('registration.backends.hmac.urls')),

    # url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name="main_page.html")),
    # url(r'^home/', TemplateView.as_view(template_name="home.html")),
    # url(r'^wallets/', TemplateView.as_view(template_name="wallets.html")),
    # url(r'^trans-history/', TemplateView.as_view(template_name="trans_history.html")),
    # url(r'^reports/', TemplateView.as_view(template_name="reports.html"), name='reports'),
    # url(r'^general/', TemplateView.as_view(template_name="home.html"), name='general'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'session_security/', include('session_security.urls')),

    url(r'^$', views.main_page),
    url(r'^home/', views.home),
    url(r'^wallets/', views.wallets),
    url(r'^trans-history/', views.trans_history),
    url(r'^reports/', views.reports, name='reports'),
    url(r'^general/', views.general, name='general'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^verif/$', views.verify_user, name='verif'),
    url(r'^sms/$', views.send_sms, name='sms'),
    url(r'^retrieve_pass/$', views.retrieve_pass, name='retrieve_pass'),
    url(r'^top-up/', views.recharge_account, name='recharge_account'),
    url(r'^bank-accounts/', views.bank_accounts, name='bank_accounts'),
)

interpay/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from django.contrib.auth.models import User
from django.utils.formats import get_format
from datetime import datetime, timedelta
from django.core.mail import send_mail
from collections import defaultdict
from django.db import models
from decimal import Decimal
import convert
import random
import time


class Manager(BaseUserManager):
    def create_user(self, USERNAME_FIELD, email, password):
        email = self.normalize_email(email)
        username = self.model.normalize_username(USERNAME_FIELD)
        user = self.model(username=username, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="UserProfile")
    password = models.CharField(max_length=10, null=False, blank=False)
    picture = models.ImageField(upload_to='userProfiles/', null=True, blank=True)
    date_of_birth = models.DateTimeField(null=False, blank=False)
    date_joined = models.DateTimeField(default=datetime.now())
    country = CountryField(default="Iran")
    national_code = models.CharField(max_length=10, null=False, blank=False)
    mobile_number = models.CharField(max_length=11, null=True, blank=True)
    email = models.EmailField(null=False, blank=False)
    # TODO : this field should not be nullable. fix it.
    national_card_photo = models.ImageField(upload_to='nationalCardScans/', null=True, blank=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    objects = Manager()

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return '{}'.format(self.user.username)

    def __unicode__(self):
        return self.user.username

        # def __init__(self, *args, **kwargs):
        #     super(UserProfile, self).__init__(*args, **kwargs)
        #     if self.instance:
        #         # we're operating on an existing object, not a new one...
        #         country = self.instance.country
        #         cities = self.fields["new_city"] = ChoiceField(choices=cities)


class CommonUser(models.Model):
    # since we might need to define a Manager model in the future, this model is named as "CommonUser"
    user_ID = models.ForeignKey(UserProfile, null=False, related_name='user_ID')

    def __str__(self):
        return '{} - {}'.format(self.customer_ID, self.user_ID.name)


class VerificationCodes(models.Model):
    user_code = models.IntegerField()
    user = models.ForeignKey(UserProfile, null=False, related_name='verif_code_user')

    def __str__(self):
        return '{} - {}'.format(self.user, self.user.name)


class Rule(models.Model):
    my_formats = get_format('DATETIME_INPUT_FORMATS')
    start_date = models.DateField()  # (required=False, input_formats=('%d/%m/%Y',))#(input_formats="%d-%b-%Y")
    end_date = models.DateField()  # (input_formats="%d-%b-%Y")
    # end_date = models.DateField()
    cur_code = models.CharField(_('cur_code'), max_length=3, default='USD')
    deposit_charge_percent = models.FloatField(default=2)
    credit_percent = models.FloatField(default=98)

    @staticmethod
    def on_date(_date, _code='USD'):
        return Rule.objects.get(start_date__lte=_date, end_date__gte=_date, cur_code=_code)


START_TIME = 0x0


def make_id():
    '''
    inspired by http://instagram-engineering.tumblr.com/post/10853187575/sharding-ids-at-instagram
    '''

    t = int(time.time() * 1000) - START_TIME
    u = random.SystemRandom().getrandbits(22)
    id = (t << 22) | u
    return id


def reverse_id(id):
    t = id >> 22
    return t + START_TIME


class BankAccount(models.Model):
    LEGAL = 1
    INDIVIDUAL = 2
    DEBIT = 1
    CREDIT = 2

    # owner_type = models.PositiveSmallIntegerField(choices=(
    #     (LEGAL, 'Legal'),
    #     (INDIVIDUAL, 'INDIVIDUAL'),
    # ), default=INDIVIDUAL)

    method = models.PositiveSmallIntegerField(choices=(
        (DEBIT, 'Debit'),
        (CREDIT, 'Credit'),
    ), default=DEBIT)
    alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
    # TODO : this validator should be placed in js as well, so the user can not type other kinds of inputs
    name = models.CharField(max_length=254)
    when_opened = models.DateField(_("Date"), default=datetime.now)
    owner = models.ForeignKey(UserProfile, related_name='w_accounts')
    cur_code = models.CharField(_('cur_code'), max_length=3, default='RLS')
    spectators = models.ManyToManyField(UserProfile, related_name='r_accounts')
    account_id = models.CharField(primary_key=True, max_length=24, validators=[alphanumeric])

    def total_value(self):
        t_value = Decimal(0)
        total_estimate = defaultdict(lambda: Decimal(0.0))
        accounts = BankAccount.objects.filter(owner=self.owner)
        for account in accounts:
            total_estimate[account.cur_code] += Decimal(convert(account.balance, account.cur_code, 'USD'))
            t_value += total_estimate[account.cur_code]

        return t_value.quantize(Decimal("0.01"), rounding=Decimal.ROUND_UP)
        # TODO define total value

    @property
    def balance(self):
        assert self.method == self.DEBIT
        today = datetime.today()
        # print 'started balance22'
        rule = Rule.on_date(self.when_opened)
        current_date = self.when_opened
        # print 'started while'
        result = 0
        while current_date <= datetime.date(today):
            #   print 'count of sets'
            print self.income_transfers.on_date(current_date).count()
            print self.deposit_set.on_date(current_date).count()
            result -= sum(x.amount for x in self.withdraw_set.on_date(current_date))
            result -= sum(x.amount for x in self.outcome_transfers.on_date(current_date))
            result += sum(x.amount for x in self.deposit_set.on_date(current_date))
            # for c,x in groupby(self.deposit_set.on_date(current_date), lambda x: x.cur_code):
            #     result[c]+= sum(y.amount for y in x)
            result += sum(x.amount for x in self.income_transfers.on_date(current_date))

            current_date += timedelta(days=1)
            print rule.deposit_charge_percent

            #   print current_date
        result *= 1 - (rule.deposit_charge_percent * 0.01)
        return result

    @property
    def debt(self):
        assert self.method == self.CREDIT
        today = time.timezone.now()
        rule = Rule.on_date(self.when_opened)
        result = 0
        current_date = self.when_opened
        while current_date <= today:
            result += sum(x.amount for x in self.withdraw_set.on_date(current_date))
            result += sum(x.amount for x in self.outcome_transfers.on_date(current_date))
            result -= sum(x.amount for x in self.deposit_set.on_date(current_date))
            result -= sum(x.amount for x in self.income_transfers.on_date(current_date))
            result *= rule.credit_percent
            current_date += timedelta(days=1)
        return result


class OperationManager(models.Manager):
    def on_date(self, date):
        return (super(OperationManager, self).get_queryset()).filter(when__gte=date, when__lte=date)


class MoneyTransfer(models.Model):
    # Inter-bank-account money transfer
    sender = models.ForeignKey(BankAccount, related_name='outcome_transfers')
    receiver = models.ForeignKey(BankAccount, related_name='income_transfers')
    date = models.DateTimeField()
    amount = models.FloatField()
    comment = models.CharField(max_length=255)
    cur_code = models.CharField(_('cur_code'), max_length=3, default='USD')
    objects = OperationManager()


class Deposit(models.Model):
    # Receiving money; Charging account.
    account = models.ForeignKey(BankAccount, related_name='deposit_set')
    amount = models.FloatField()
    banker = models.ForeignKey(UserProfile)
    date = models.DateTimeField(default=datetime.now)
    cur_code = models.CharField(_('cur_code'), max_length=3, default='USD')
    objects = OperationManager()
    tracking_code = models.IntegerField(default='123')
    status = models.BooleanField(default=False)


class Withdraw(models.Model):
    account = models.ForeignKey(BankAccount, related_name='withdraw_set')
    amount = models.FloatField()
    banker = models.ForeignKey(User)
    date = models.DateTimeField()
    cur_code = models.CharField(_('cur_code'), max_length=3, default='USD')
    objects = OperationManager()

interpay/templates/forgot_password.html
{% extends 'registeration_form.html' %}
{% load staticfiles %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<header>
    <div class="top-bar">
        <div class="container" style="color: white;">
            <b>{% block header_title %}
                Welcome to InterPay Iran (Rizpardakht)
            {% endblock %}</b>

            <div class="row">
                <div id="number" class="col-sm-6 col-xs-4"></div>
                <div id="social" class="col-sm-6 col-xs-8"></div>
            </div>
        </div>
    </div>
    <nav></nav>
</header>

<section>
    <div class="container">
        <div class="row">
            {% block main-cont %}
                <div class="col-xs-12" style="text-align: center ">
                    <div class="form-wrapper" id="login-form-wrapper">
                        <div>
                            {% block message %}
                                {% if msg %}
                                    #TODO this style should be omitted and implemented via registration-form.css
                                    <div class="form-msg"
                                         style="padding: 10px 5px;color: red;font-size: small;margin-top: 5px"><i
                                            class="fa fa-exclamation-triangle" style="color: red"
                                            aria-hidden="true"></i> {{ msg }}</div>
                                {% endif %}
                            {% endblock %}</div>
                        <hr>
                        <form id="login_form" method="post" action="/login/">
                            {% csrf_token %}

                            <div id="lgn-btn-div" style="text-align: center"><input
                                    id="login-btn"
                                    class="btn btn-info" type="submit"
                                    value="{% trans 'Login' %}"/></div>
                        </form>
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</section>
</body>
</html>

interpay/templates/general.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        <h3 class="page-title">{% block title %}{% trans 'General' %}{% endblock %}</h3>
    </title>
</head>
<body>
{% block cont-header %}
    <div>
        <h3 class="page-title">
            {% trans 'General' %}
        </h3>
    </div>
{% endblock %}
{% block cont-body %}
    {% trans 'This page is still under construction ... . we will be at your service soon.' %}
{% endblock %}
</body>
</html>

interpay/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="../static/jquery/jquery-1.10.2.min.js"></script>
    {% block CSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    {% endblock %}
    <meta charset="UTF-8">
    <title>{% block title %}
        {% trans 'Home Page' %}
    {% endblock %}</title>
</head>
<body>
{% block cont-header %}
    <div id="welcome-msg" >
        <h3 class="page-title"> {% trans "Welcome to interpay" %}</h3>
    </div>
{% endblock %}
{% block cont-body %}
    <div id="interpay-desc">
        <p>
            {% trans 'Interpay is an online electronic service which provides a safe and secure platform for business transactions and e-commerce. No matter you are the merchant or the consumer, we will bring you an enjoyable experience of transaction.' %}
        </p>
    </div>
{% endblock %}

</body>
</html>

interpay/templates/index.html
{% extends 'registeration_form.html' %}
{% load staticfiles %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>InterPay Iran</title>
    {% block CSS %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}
    {% block style %}
        <style>
            {% ifequal LANGUAGE_CODE 'fa-ir' %}
                #login-box-hdr {
                    direction: rtl;
                }
            {% endifequal %}
        </style>
    {% endblock %}
</head>
<body>
<script>
    {% block script %}
        function forgot_pass() {
            swal({
                title: "Password Retrieval",
                text: "Enter your phone number",
                type: "input",
                showCancelButton: true,
                closeOnConfirm: false,
                animation: "slide-from-top",
                inputPlaceholder: "Phone number"
            }, function (inputValue) {
                if (inputValue === "") {
                    swal.showInputError("You need enter your number");
                    return false
                }
                var postUrl = "/retrieve_pass/";
                $.ajax({
                    url: postUrl,
                    type: 'POST',
                    data: {'mobile_no': inputValue},
                    traditional: true,
                    dataType: 'html',
                    success: function (result) {
                        // for now, this method is the same as sending a common sms, but it has to be improved
                        // to generating a more secure password and email it as well as SMSing #TODO
                        swal(result, "A new password has been sent to your phone.", "success");
                    }
                });
            });
        }
    {% endblock %}

</script>
<header>
    <div class="top-bar">
        <div class="container" style="color: white;">
            <b>{% block header_title %}
                Welcome to InterPay Iran (Rizpardakht)
            {% endblock %}</b>

            <div class="row">
                <div id="number" class="col-sm-6 col-xs-4"></div>
                <div id="social" class="col-sm-6 col-xs-8"></div>
            </div>
        </div>
    </div>
    <nav></nav>
</header>
<section>
    <div class="container">
        <div class="row">
            {% block main-cont %}

                <div class="col-xs-12" style="text-align: center ">
                    <h3 style="margin-top: 40px">{% trans 'Welcome to Interpay Iran' %}</h3>

                    <div class="form-wrapper" id="login-form-wrapper">
                        <div id="login-box-hdr" style="font-size: larger"><i class="fa fa-sign-in"
                                                                             style="padding-right: 5px"
                                                                             aria-hidden="true"></i>
                            {% trans 'Login to Interpay' %}
                        </div>
                        <div>{% block message %}
                            {% if msg %}
                                {#                                TODO this style should be omitted and implemented via registration-form.css #}
                                <div class="form-msg"
                                     style="padding: 10px 5px;color: red;font-size: small;margin-top: 5px"><i
                                        class="fa fa-exclamation-triangle" style="color: red"
                                        aria-hidden="true"></i> {{ msg }}</div>
                            {% endif %}
                        {% endblock %}</div>
                        <hr>
                        <form id="login_form" method="post" action="/login/">
                            {% csrf_token %}
                            <div id="username-div"><input class="login-form-field" type="text" name="username"
                                                          id="username" value=""
                                                          placeholder="Username" size="50"/>
                            </div>
                            <div id="password-div"><input class="login-form-field" type="password" name="password"
                                                          id="password" value=""
                                                          placeholder="Password" size="50"/>
                            </div>
                            {#                            <input type="text" id="mobile_number" name="mobile_number" placeholder="111-111-1111"#}
                            {#                                   required>#}
                            {#                            <button class="btn" type="button" onClick="send_pin()"><i class="icon-share"></i> Get PIN#}
                            {#                            </button>#}
                            <div id="lgn-btn-div" style="text-align: center"><input
                                    id="login-btn"
                                    class="btn btn-info" type="submit"
                                    value="{% trans 'Login' %}"/></div>
                        </form>
                        <div id="forgot-pass-div" style="text-align: center"><h6><a
                                onclick="forgot_pass()">{% trans 'Forgot password or account disabled ?' %}</a></h6>
                        </div>
                    </div>
                    <div id="register-link-div">
                        <h6>{% trans "Don't have an account yet?" %}</h6>
                        {% ifequal LANGUAGE_CODE 'en-gb' %}
                            <a id="register-link" href="/register/">
                        {% else %}
                            <a id="register-link" href="/fa-ir/register/">
                        {% endifequal %}
                        {% trans 'Create One!' %}
                        </a><br/>

                        {#                        <a id="register-link" href="/register/">{% trans 'Create One!' %}</a>#}
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</section>

</body>
</html>

interpay/templates/top_up.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block CSS %}
        <link rel="stylesheet" href="{% static 'css/top_up.css' %}">
    {% endblock %}
    {% block JS %}
    {% endblock %}
    <meta charset="UTF-8">
    <title>{% block title %}
        {% trans 'Top Up by Credit Card' %}
    {% endblock %}</title>
</head>
<body>
<script>
    {% block script %}
        $(document).ready(function () {
            $("#id_amount").keydown(function (event) {
                if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || event.keyCode == 13 ||
                        (event.keyCode == 65 && event.ctrlKey === true) ||
                        (event.keyCode >= 35 && event.keyCode <= 39)) {
                }
                else {
                    if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
                        event.preventDefault();
                    }
                }
            });

            {% ifequal LANGUAGE_CODE 'fa-ir' %}
                $(".recharge-form-input").addClass('pull-right');
                $(".recharge-form-label").addClass('pull-right');
                $(".recharge-form-label").css({'text-align': 'left'});
                console.log($(".recharge-form-label").className);
            {% endifequal %}

        });

        function showZPTrust() {
            var thewindow = window.open("https://www.zarinpal.com/webservice/verifyWebsite/" + window.location.hostname,
                    null, "width=656, height=500, scrollbars=no, resizable=no");
        }
    {% endblock %}
</script>

{% block cont-header %}
    <div id="topup_title">
        <h3 class="page-title"> {% trans "Recharge wallet using credit card" %}</h3>
    </div>
{% endblock %}
{% block cont-body %}
    <div class="row" style="display: table;width: 100%">
        <div class="col-xs-12">
            <form id="recharge-form" class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group recharge-form-parts">
                    <label for="payment-gateway" class="col-sm-3 recharge-form-label"
                           style="margin-top: 8px">{% trans 'Payment Type' %}</label>
                    <div class="col-sm-9">
                        <div class="control-group">
                            <div class="radio">

                                <input type="radio" name="payment-gateway" checked>
                                <a href="javascript:showZPTrust();"
                                   title="دروازه پرداخت معتبر"><img src="{% static 'images/Zarinpal.png' %}"
                                                                    alt="دروازه پرداخت معتبر"></a>
                                {#                                <script src="https://www.zarinpal.com/webservice/TrustCode"#}
                                {#                                        type="text/javascript"></script>#}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="space"></div>
                <div class="form-group">
                    <label class="col-sm-3 recharge-form-label"
                           style="margin-top: 8px">{% trans 'Wallet Type' %}</label>
                    <div class="col-sm-9">
                        <div class="col-xs-6 recharge-form-input" id="recharge-currency">{{ form.currency }}</div>
                    </div>
                </div>
                <div class="space"></div>
                <div class="form-group">
                    <label class="col-sm-3 recharge-form-label"
                           style="margin-top: 8px">{% trans 'Recharge Amount' %}</label>
                    <div class="col-sm-9">
                        <div class="col-xs-6 recharge-form-input" id="id_amount_div">{{ form.amount }}</div>
                    </div>
                </div>
                <div class="space"><br></div>

                <div id="recharge-form-btns" class="clearfix">
                    <div class="col-md-offset-3 col-md-9">
                        {#                        <div class="col-md-3">#}
                        <button class="btn btn-info recharge-form-btn" type="submit"><i
                                class="fa fa-check"></i> {% trans 'Charge' %}
                        </button>
                        {#                        </div>#}
                        {#                        <div class="col-md-3">#}
                        <button class="btn recharge-form-btn" type="reset"><i
                                class="fa fa-undo"></i> {% trans 'Reset' %}</button>
                        {#                        </div>#}
                    </div>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="page-header">
        <h3 class="page-title">{% trans 'Recharge Wallet History' %}</h3>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div id="tab-wrapper" style="margin-right: 0 !important;margin-left: 0 !important" class="row tab-wrapper">
                <div id="wal-tab-searchbar" class="row ">
                <span id="display-records" class="col-sm-6">
                    <i class="fa fa-eye" aria-hidden="true">
                        <select>
                            <option value="5">5</option>
                            <option value="10">10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                            <option value="40">40</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                            <option value="500">500</option>
                        </select>
                    </i>
                </span>
                    <span id="search" class="col-sm-6">
                    <i class="fa fa-search" aria-hidden="true">
                            <input type="text" id="search-txtbox">
                    </i>
                </span>
                </div>
                <table id="wal-tab">
                    <thead>
                    <tr class="table-header-row">
                        <th class="table-header-cell">
                            {% trans 'Index' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Recharge ID' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Date' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Wallet Code' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Currency' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Card Type' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Amount' %}
                        </th>
                        <th class="table-header-cell">
                            {% trans 'Status' %}
                        </th>
                        <th class="table-header-cell"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for d in deposit_set %}
                        <tr>
                            <td class="table-cell">{{ forloop.counter }}</td>
                            <td class="table-cell">{{ d.id }}</td>
                            <td class="table-cell">{{ d.date }}</td>
                            <td class="table-cell">{{ d.account.account_id }}</td>
                            <td class="table-cell">{{ d.cur_code }}</td>
                            <td class="table-cell"></td>
                            <td class="table-cell">{{ d.amount }}</td>
                            <td class="table-cell">{% ifequal d.status True %}
                                Successful
                            {% endifequal %}
                                Failed
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
                <div id="wal-tab-footer" class="row" style="margin-left: 0 !important;margin-right: 0 !important;">
                    <h5 style="padding-left: 20px" class="col-sm-8">Showing {{ 1 }} to {{ x }} of entries</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>